# Added by huofudong for TCT-987 on 20240115 begin
ifeq ($(ODM_CUSTOM_FACTORY_BUILD),true)
obj-$(CONFIG_INPUT_SAR) += sensor_fac_node.o
endif
# Added by huofudong for TCT-987 on 20240115 end

# Added by huofudong for QN7026A-29 on 20240123 begin
obj-$(CONFIG_INPUT_SAR) += sensor_user_node.o
# Added by huofudong for QN7026A-29 on 20240123 end

obj-$(CONFIG_SAR_SX933X)+= sx933x.o

